CREATE DATABASE ANFIELD_AIRLINES;
USE ANFIELD_AIRLINES;

SHOW TABLES;

SELECT * FROM ANFIELD_AIRLINES;
DESC ANFIELD_AIRLINES;


# 1 TOTAL PASSENGERS
SELECT COUNT(*) AS TOTAL_PASSENGERS
FROM ANFIELD_AIRLINES;


# 2 SATISFIED PASSENGERS COUNT
SELECT * FROM ANFIELD_AIRLINES;

SELECT SATISFACTION, COUNT(SATISFACTION) AS SATISFIED_PASSENGERS
FROM ANFIELD_AIRLINES
WHERE SATISFACTION = 'SATISFIED'
GROUP BY SATISFACTION;


# 3 AVERAGE FLIGHT DISTANCE
SELECT * FROM ANFIELD_AIRLINES;

SELECT ROUND(AVG(FLIGHT_DISTANCE)) AS AVERAGE_FLIGHT_DISTANCE
FROM ANFIELD_AIRLINES;

# 4 AVERAGE PASSENGER AGE
SELECT ROUND(AVG(AGE_)) AS AVERAGE_PASSENGER_AGE
FROM ANFIELD_AIRLINES;


# 5 AVERAGE DEPARTURE DELAY IN MINUTES
SELECT AVG(DEPARTURE_DELAY) AS AVG_DEPARTURE_DELAY
FROM ANFIELD_AIRLINES;


# 6 AVERAGE ARRIVAL DELAY IN MINUTES
SELECT AVG(ARRIVAL_DELAY) AS AVG_ARRIVAL_DELAY
FROM ANFIELD_AIRLINES;


# 7 OVERALL PASSENGER SATISFACTION
SELECT SATISFACTION, COUNT(SATISFACTION) AS SATISFIED_PASSENGERS
FROM ANFIELD_AIRLINES
GROUP BY SATISFACTION;


# 8 PASSENGER SATISFACTION BY CUSTOMER TYPE
SELECT * FROM ANFIELD_AIRLINES;

SELECT CUSTOMER_TYPE, SATISFACTION, COUNT(SATISFACTION) AS CUSTOMER_TYPE_SATISFACTION
FROM ANFIELD_AIRLINES
GROUP BY CUSTOMER_TYPE, SATISFACTION
ORDER BY CUSTOMER_TYPE;


# 9 PASSENGER SATISFACTION BY CLASS
SELECT * FROM ANFIELD_AIRLINES;

SELECT CLASS, SATISFACTION, COUNT(CLASS) AS CUSTOMER_TYPE_SATISFACTION
FROM ANFIELD_AIRLINES
GROUP BY CLASS, SATISFACTION
ORDER BY CLASS;


# 10 PASSENGER PROFILE BY AGE AND CLASS
SELECT * FROM ANFIELD_AIRLINES;

SELECT
CASE WHEN AGE_ >= 5 AND AGE_<= 12 THEN "CHILD"
WHEN AGE_>=13 AND AGE_<= 19 THEN "TEENAGER"
WHEN AGE_>=20 AND AGE_>= 39 THEN "YOUNG ADULT"
WHEN AGE_>=40 AND AGE_<= 59 THEN "MIDDLE-AGED ADULT"
ELSE "60 +" END AS AGE_CATEGORY,
CLASS, COUNT(CLASS) AS TOTAL_PASSENGERS
FROM ANFIELD_AIRLINES
GROUP BY AGE_CATEGORY, CLASS
ORDER BY AGE_CATEGORY;


# 11 PASSENGERS' PREFERANCE BY FLIGHT DISTANCE
SELECT * FROM ANFIELD_AIRLINES;

SELECT
CASE WHEN FLIGHT_DISTANCE>=0 AND FLIGHT_DISTANCE<932 THEN "SHORT LEG"
WHEN FLIGHT_DISTANCE>=932 AND FLIGHT_DISTANCE<2485 THEN "MEDIUM LEG"
ELSE "LONG LEG" END AS FLIGHT_LEG,
CLASS, COUNT(CLASS) AS TOTAL_PASSENGERS
FROM ANFIELD_AIRLINES
GROUP BY FLIGHT_LEG, CLASS
ORDER BY FLIGHT_LEG DESC;


# 12 ON BOARD SERVICES
SELECT * FROM ANFIELD_AIRLINES;
#ONBOARD SERVICE, SEAT COMFORT, LEG ROOM SERVICE, CLEANLINESS, FOOD AND DRINK, INFLIGHT SERVICE, INFLIGHT WIFI SERVICE, INFLIGHT ENTERTAINMENT

#AVERAGE ONBOARD SERVICE RATING
SELECT AVG(ONBOARD_SERVICE) AS AVG_ONBOARD_SERVICE_RATING
FROM ANFIELD_AIRLINES;

#AVERAGE SEAT COMFORT RATING
SELECT AVG(SEAT_COMFORT) AS AVG_SEAT_COMFORT_RATING
FROM ANFIELD_AIRLINES;

#AVERAGE LEG ROOM SERVICE RATING
SELECT AVG(LEG_ROOM_SERVICE) AS AVG_LEG_ROOM_SERVICE_RATING
FROM ANFIELD_AIRLINES;

#AVERAGE CLEANLINESS RATING
SELECT AVG(CLEANLINESS) AS AVG_CLEANLINESS_RATING
FROM ANFIELD_AIRLINES;

#AVERAGE FOOD AND DRINK RATING
SELECT AVG(FOOD_AND_DRINK) AS AVG_FOOD_AND_DRINK_RATING
FROM ANFIELD_AIRLINES;

#AVERAGE INFLIGHT SERVICE RATING
SELECT AVG(INFLIGHT_SERVICE) AS AVG_INFLIGHT_SERVICE_RATING
FROM ANFIELD_AIRLINES;

#AVERAGE INFLIGHT WIFI SERVICE RATING
SELECT AVG(INFLIGHT_WIFI_SERVICE) AS AVG_INFLIGHT_WIFI_SERVICE_RATING
FROM ANFIELD_AIRLINES;

#AVERAGE INFLIGHT ENTERTAINMENT RATING
SELECT AVG(IN_FLIGHT_ENTERTAINMENT) AS AVG_INFLIGHT_ENTERTAINMENT_RATING
FROM ANFIELD_AIRLINES;


# 13 AIRLINE SERVICES
SELECT * FROM ANFIELD_AIRLINES;
#EASE OF ONLINE BOOKING, CHECK-IN SERVICE, ONLINE BOARDING, GATE LOCATION, BAGGAGE HANDLING

# AVERAGE EASE OF ONLINE BOOKING RATING
SELECT AVG(EASE_OF_ONLINE_BOOKING) AS AVG_EASE_OF_ONLINE_BOOKING_RATING
FROM ANFIELD_AIRLINES;

# AVERAGE CHECK-IN SERVICE RATING
SELECT AVG(CHECK_IN_SERVICE) AS AVG_CHECK_IN_SERVICE_RATING
FROM ANFIELD_AIRLINES;

# AVERAGE ONLINE BOARDING RATING
SELECT AVG(ONLINE_BOARDING) AS AVG_ONLINE_BOARDING_RATING
FROM ANFIELD_AIRLINES;

# AVERAGE GATE LOCATION RATING
SELECT AVG(GATE_LOCATION) AS AVG_GATE_LOCATION_RATING
FROM ANFIELD_AIRLINES;

# AVERAGE BAGGAGE HANDLING RATING
SELECT AVG(BAGGAGE_HANDLING) AS AVG_BAGGAGE_HANDLING_RATING
FROM ANFIELD_AIRLINES;